SubsetTypes.dfy(7,18): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(8,9): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(10,23): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(11,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(15,15): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(16,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(19,11): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(21,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(23,8): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(30,4): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(31,7): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(42,24): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(44,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(45,9): Error: value does not satisfy the subset constraints of 'int ~> nat'
Execution trace:
    (0,0): anon0
    SubsetTypes.dfy(45,10): anon3_Else
SubsetTypes.dfy(50,15): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(52,9): Error: value does not satisfy the subset constraints of 'int -> nat'
Execution trace:
    (0,0): anon0
    SubsetTypes.dfy(51,15): anon3_Else
SubsetTypes.dfy(57,4): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(64,23): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(65,9): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(67,28): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(68,9): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(72,20): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(73,6): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(76,11): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(78,15): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(80,8): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(87,4): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(88,7): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(99,24): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(101,15): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(102,9): Error: value does not satisfy the subset constraints of 'set<int> ~> set<nat>'
Execution trace:
    (0,0): anon0
    SubsetTypes.dfy(102,10): anon3_Else
SubsetTypes.dfy(107,15): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(109,9): Error: value does not satisfy the subset constraints of 'set<int> -> set<nat>'
Execution trace:
    (0,0): anon0
    SubsetTypes.dfy(108,15): anon3_Else
SubsetTypes.dfy(114,4): Error: value does not satisfy the subset constraints of 'set<nat>'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Else
SubsetTypes.dfy(124,32): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
SubsetTypes.dfy(126,20): Error: value does not satisfy the subset constraints of 'nat'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(136,25): Error: value does not satisfy the subset constraints of 'int ~> int'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
SubsetTypes.dfy(137,25): Error: value does not satisfy the subset constraints of 'int ~> int'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(142,25): Error: value does not satisfy the subset constraints of 'int ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
SubsetTypes.dfy(144,25): Error: value does not satisfy the subset constraints of 'int ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
SubsetTypes.dfy(145,25): Error: value does not satisfy the subset constraints of 'int ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(158,25): Error: value does not satisfy the subset constraints of 'nat ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
SubsetTypes.dfy(160,25): Error: value does not satisfy the subset constraints of 'nat ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
SubsetTypes.dfy(170,20): Error: cannot establish the existence of LHS values that satisfy the such-that predicate
Execution trace:
    (0,0): anon0
SubsetTypes.dfy(183,11): Error: value does not satisfy the subset constraints of 'int ~> nat'
Execution trace:
    (0,0): anon0
    (0,0): anon29_Then
    SubsetTypes.dfy(183,12): anon30_Else
SubsetTypes.dfy(200,25): Error: value does not satisfy the subset constraints of 'Person'
Execution trace:
    (0,0): anon0
    (0,0): anon16_Then
    SubsetTypes.dfy(199,26): anon17_Else
    SubsetTypes.dfy(200,26): anon18_Else
SubsetTypes.dfy(205,23): Error: value does not satisfy the subset constraints of 'Person'
Execution trace:
    (0,0): anon0
    (0,0): anon16_Then
    SubsetTypes.dfy(199,26): anon17_Else
    SubsetTypes.dfy(200,26): anon18_Else
    (0,0): anon7
    SubsetTypes.dfy(202,25): anon19_Else
    SubsetTypes.dfy(203,25): anon20_Else
    SubsetTypes.dfy(204,24): anon21_Else
    SubsetTypes.dfy(205,24): anon22_Else
SubsetTypes.dfy(210,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
SubsetTypes.dfy(212,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
    SubsetTypes.dfy(212,28): anon13_Else
SubsetTypes.dfy(214,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon14_Then
SubsetTypes.dfy(216,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon15_Then
SubsetTypes.dfy(222,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
SubsetTypes.dfy(224,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
    SubsetTypes.dfy(224,29): anon13_Else
SubsetTypes.dfy(226,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon14_Then
SubsetTypes.dfy(228,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon15_Then
SubsetTypes.dfy(236,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon17_Then
SubsetTypes.dfy(238,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon18_Then
SubsetTypes.dfy(241,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon19_Then
    SubsetTypes.dfy(240,27): anon20_Else
SubsetTypes.dfy(243,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon21_Then
    SubsetTypes.dfy(243,26): anon22_Else
SubsetTypes.dfy(245,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon23_Then
    SubsetTypes.dfy(245,27): anon24_Else
SubsetTypes.dfy(255,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(258,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon10_Then
SubsetTypes.dfy(261,11): Error: value does not satisfy the subset constraints of 'array<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then
SubsetTypes.dfy(264,11): Error: value does not satisfy the subset constraints of 'array<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon12_Then
SubsetTypes.dfy(280,11): Error: value does not satisfy the subset constraints of 'seq<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon15_Then
SubsetTypes.dfy(289,11): Error: value does not satisfy the subset constraints of 'seq<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon18_Then
SubsetTypes.dfy(300,11): Error: value does not satisfy the subset constraints of 'Cell<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon14_Then
SubsetTypes.dfy(302,11): Error: value does not satisfy the subset constraints of 'Cell<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon15_Then
SubsetTypes.dfy(306,11): Error: value does not satisfy the subset constraints of 'Cell<Person?>'
Execution trace:
    (0,0): anon0
    (0,0): anon17_Then
SubsetTypes.dfy(308,11): Error: value does not satisfy the subset constraints of 'Cell<Person>'
Execution trace:
    (0,0): anon0
    (0,0): anon18_Then
SubsetTypes.dfy(326,28): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon6_Then
SubsetTypes.dfy(327,30): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
SubsetTypes.dfy(328,30): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
SubsetTypes.dfy(329,38): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(334,33): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon4_Then
SubsetTypes.dfy(335,39): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon5_Then
SubsetTypes.dfy(340,28): Error: value does not satisfy the subset constraints of 'byte'
Execution trace:
    (0,0): anon0
    (0,0): anon7_Then
SubsetTypes.dfy(341,29): Error: value does not satisfy the subset constraints of 'seq<byte>'
Execution trace:
    (0,0): anon0
    (0,0): anon8_Then
SubsetTypes.dfy(342,29): Error: value does not satisfy the subset constraints of 'set<byte>'
Execution trace:
    (0,0): anon0
    (0,0): anon9_Then
SubsetTypes.dfy(343,29): Error: value does not satisfy the subset constraints of 'multiset<byte>'
Execution trace:
    (0,0): anon0
    (0,0): anon10_Then
SubsetTypes.dfy(344,29): Error: value does not satisfy the subset constraints of 'map<byte, byte>'
Execution trace:
    (0,0): anon0
    (0,0): anon11_Then

Dafny program verifier finished with 5 verified, 81 errors
